---
- name: caddy_restart
  ansible.builtin.service:
    name: caddy.service
    state: restarted
    enabled: true

- name: caddy_service_reload
  listen: service modified
  ansible.builtin.systemd:
    daemon_reload: true
