---
- name: Caddy service reload
  listen: service modified
  ansible.builtin.systemd:
    daemon_reload: true

- name: Caddy restart
  ansible.builtin.service:
    name: caddy.service
    state: restarted
    enabled: true
