---
- name: Converge
  hosts: all
  become: true
  gather_facts: true
  vars:
    caddy_config_snippets:
      - name: tls
        config: |
          /etc/ssl/cert.pem /etc/ssl/key.pem
    caddy_config_sites:
      - name: example.com
        config: |
          root * /var/www
          file_server

  roles:
    - role: "ansible-role-caddy"
