---
- name: Converge
  hosts: all
  become: true
  gather_facts: true
  vars:
    caddy_config_snippets:
      - name: tls
        config: |
          tls /etc/ssl/cert.pem /etc/ssl/key.pem
    caddy_config_sites:
      - name: :80
        config: |
          root * /usr/share/caddy
          file_server

  roles:
    - role: "ansible-role-caddy"
