---
- name: Prepare
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Create private key
      community.crypto.openssl_privatekey:
        path: /etc/ssl/key.pem
    - name: Create simple self-signed certificate
      community.crypto.x509_certificate:
        path: /etc/ssl/cert.pem
        privatekey_path: /etc/ssl/key.pem
        provider: selfsigned

  roles:
    - role: mullholland.repository_caddy
