---
- name: Verify
  hosts: all
  become: true
  gather_facts: true
  vars:
    verify:
      package: "caddy"
      config_file: "/etc/caddy/Caddyfile"
      config_line: "metrics"
      config_line2: "tls"
      config_line3: "file_server"
      config_owner: "root"
      config_group: "root"
      config_mode: "0644"
      daemon: "caddy"

  tasks:
    - name: SmokeTests
      ansible.builtin.debug:
        msg:
          - "ansible_version => {{ansible_version}}"
          - "ansible_distribution => {{ ansible_distribution }}"
          - "ansible_distribution_major_version => {{ ansible_distribution_major_version }}"
          - "ansible_os_family  => {{ ansible_os_family}}"
          - "ansible_system  => {{ ansible_system }}"

    - name: Check if package is installed
      ansible.builtin.package:
        name: "{{ verify.package }}"
        state: present
      check_mode: true
      register: package_installed
      failed_when: (package_installed is changed) or (package_installed is failed)

    - name: check {{ verify.config_file }} conf file for globals
      lineinfile:
        name: "{{ verify.config_file }}"
        line: "{{ verify.config_line }}"
        state: present
        owner: "{{ verify.config_owner }}"
        group: "{{ verify.config_group }}"
        mode: "{{ verify.config_mode }}"
      check_mode: true
      register: molecule_hcl
      failed_when: (molecule_hcl is changed) or (molecule_hcl is failed)

    - name: check {{ verify.config_file }} conf file for snippets
      lineinfile:
        name: "{{ verify.config_file }}"
        line: "{{ verify.config_line2 }}"
        state: present
        owner: "{{ verify.config_owner }}"
        group: "{{ verify.config_group }}"
        mode: "{{ verify.config_mode }}"
      check_mode: true
      register: molecule_hcl
      failed_when: (molecule_hcl is changed) or (molecule_hcl is failed)

    - name: check {{ verify.config_file }} conf file for sites
      lineinfile:
        name: "{{ verify.config_file }}"
        line: "{{ verify.config_line3 }}"
        state: present
        owner: "{{ verify.config_owner }}"
        group: "{{ verify.config_group }}"
        mode: "{{ verify.config_mode }}"
      check_mode: true
      register: molecule_hcl
      failed_when: (molecule_hcl is changed) or (molecule_hcl is failed)

    - name: check {{ verify.daemon }} daemon
      service:
        name: "{{ verify.daemon }}"
        state: started
        enabled: true
      check_mode: true
      register: molecule_service
      failed_when: (molecule_service is changed) or (molecule_service is failed)
